### ISSUE TITLE
Any plans to push this further?

### ISSUE THREAD

**Issue by tomek-he-him** [Jam3/tooler#2]
I’ve written a script runner for one of our projects.

``` js
`Usage:  runner.js <script> (...<args>)

<script> should be the basename of an executable file in the same folder
as I’m in (\`${__dirname}\`).
The file must have the extension \`.js\` or \`.sh\`.

<args> are passed on directly to the script as arguments.
`
```

The runner is there for tooler (`"tooler": "./scripts/runner.js"`). You can call `tooler release` instead of `../../../scripts/release.js` and `tooler dist` instead of `../../../scripts/dist.sh`.

I can imagine I’d want such a thing in any other project that uses _tooler_. Would you be interested in integrating the runner into _tooler_ itself?

**Comment by mattdesl** [comment]
Hmm, we are using tooler currently here:
https://github.com/Jam3/vue-budo-example#tooler

The intent is that `tooler` is just a generic way to launch a node script with correct cwd. It's up to you what to do with the script, like running something in your base `scripts/` folder or launching a dev server for a specific frontend component (our usage).

:smile:

**Comment by tomek-he-him** [comment]
Alright, thanks for clearing this up!

Yeah, we also need the correct cwd. It’s just that we have more than one script.
